hi

diff --git a/functions/dialogs/confirm-command b/functions/dialogs/confirm-command
--- a/functions/dialogs/confirm-command
+++ b/functions/dialogs/confirm-command
@@ -1,18 +1,19 @@
 #!/usr/bin/env zsh
 confirm-command() {
     local command="$@"
+    local commandFormatted=$(format-args "$command")
     local prefix="$(format-cmd "confirm-command")"
-    gum confirm "$prefix Execute command '$(format-args "$command")'?" || {
-        echo-info "$prefix Command '$(format-args "$command")' was not confirmed."
+    gum confirm "Execute command '$commandFormatted'?" || {
+        echo-info "$prefix Command '$commandFormatted' was not confirmed."
         return $CODE_NOT_FOUND
     }
-    echo-debug "$prefix Command '$(format-args "$command")' was confirmed."
+    echo-debug "$prefix Command '$commandFormatted' was confirmed."
     eval "$command"
     local returnCode=$?
     if [[ $returnCode -ne 0 ]]; then
-        echo-error "$prefix Command '$(format-args "$command")' failed with return code $returnCode."
+        echo-error "Command '$commandFormatted' failed with return code $returnCode."
     else
-        echo-success "$prefix Command '$(format-args "$command")' executed successfully."
+        echo-success "Command '$commandFormatted' executed successfully."
     fi
     return $returnCode
 }
